// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChoThueThietBiXD.Data;

namespace WebChoThueThietBiXD.Migrations
{
    [DbContext(typeof(WebChoThueThietBiXDContext))]
    [Migration("20240603145347_updateKhachhangNhanvien")]
    partial class updateKhachhangNhanvien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ChiTietPhieuDat", b =>
                {
                    b.Property<int>("maChiTietPhieuDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("giaThueNgay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("maPhieuDat")
                        .HasColumnType("int");

                    b.Property<int>("maThietBi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayBatDauThue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKetThucThue")
                        .HasColumnType("datetime2");

                    b.Property<int>("soLuongThue")
                        .HasColumnType("int");

                    b.HasKey("maChiTietPhieuDat");

                    b.HasIndex("maPhieuDat");

                    b.HasIndex("maThietBi");

                    b.ToTable("ChiTietPhieuDat");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.DanhMucThietBi", b =>
                {
                    b.Property<int>("maDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maDanhMuc");

                    b.ToTable("DanhMucThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.DonHang", b =>
                {
                    b.Property<int>("maDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("maNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("maPhieuDat")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("trangThaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maDonHang");

                    b.HasIndex("maNhanVien");

                    b.HasIndex("maPhieuDat");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.GioHang", b =>
                {
                    b.Property<int>("maThietBi")
                        .HasColumnType("int");

                    b.Property<int>("maTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("maThietBi", "maTaiKhoan");

                    b.HasIndex("maTaiKhoan");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.Hang", b =>
                {
                    b.Property<int>("maHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maHang");

                    b.ToTable("Hang");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.HinhAnhThietBi", b =>
                {
                    b.Property<int>("maHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("hinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("maThietBi")
                        .HasColumnType("int");

                    b.HasKey("maHinhAnh");

                    b.HasIndex("maThietBi");

                    b.ToTable("HinhAnhThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.KhachHang", b =>
                {
                    b.Property<int>("maKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("maTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tenKhachHang")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("maKhachHang");

                    b.HasIndex("maTaiKhoan");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.NhanVien", b =>
                {
                    b.Property<int>("maNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("maTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("soDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tenNhanVien")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("tienLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("maNhanVien");

                    b.HasIndex("maTaiKhoan");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.PhieuDat", b =>
                {
                    b.Property<int>("maPhieuDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diaCHiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ghiChu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("maKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayTaoPhieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("soDienThoaiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("trangThaiPhieuDat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maPhieuDat");

                    b.HasIndex("maKhachHang");

                    b.ToTable("PhieuDat");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.TaiKhoan", b =>
                {
                    b.Property<int>("maTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("maVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("tenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maTaiKhoan");

                    b.HasIndex("maVaiTro");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ThietBi", b =>
                {
                    b.Property<int>("maThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("giaThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("maDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("maHang")
                        .HasColumnType("int");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("soLuongCon")
                        .HasColumnType("int");

                    b.Property<string>("tenThietBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maThietBi");

                    b.HasIndex("maDanhMuc");

                    b.HasIndex("maHang");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.VaiTro", b =>
                {
                    b.Property<int>("maVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ChiTietPhieuDat", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.PhieuDat", "PhieuDat")
                        .WithMany("ChiTietPhieuDats")
                        .HasForeignKey("maPhieuDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebChoThueThietBiXD.Models.ThietBi", "ThietBi")
                        .WithMany("ChiTietPhieuDats")
                        .HasForeignKey("maThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuDat");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.DonHang", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.NhanVien", "NhanVien")
                        .WithMany("DonHangs")
                        .HasForeignKey("maNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebChoThueThietBiXD.Models.PhieuDat", "PhieuDat")
                        .WithMany("DonHangs")
                        .HasForeignKey("maPhieuDat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuDat");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.GioHang", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("GioHangs")
                        .HasForeignKey("maTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebChoThueThietBiXD.Models.ThietBi", "ThietBi")
                        .WithMany("GioHangs")
                        .HasForeignKey("maThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.HinhAnhThietBi", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.ThietBi", "ThietBi")
                        .WithMany("HinhAnhThietBis")
                        .HasForeignKey("maThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.KhachHang", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("khachHangs")
                        .HasForeignKey("maTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.NhanVien", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("NhanViens")
                        .HasForeignKey("maTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.PhieuDat", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.KhachHang", "KhachHang")
                        .WithMany("PhieuDats")
                        .HasForeignKey("maKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.TaiKhoan", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("maVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ThietBi", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.DanhMucThietBi", "DanhMucThietBi")
                        .WithMany("ThietBis")
                        .HasForeignKey("maDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebChoThueThietBiXD.Models.Hang", "Hang")
                        .WithMany("ThietBis")
                        .HasForeignKey("maHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMucThietBi");

                    b.Navigation("Hang");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.DanhMucThietBi", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.Hang", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.KhachHang", b =>
                {
                    b.Navigation("PhieuDats");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.NhanVien", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.PhieuDat", b =>
                {
                    b.Navigation("ChiTietPhieuDats");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.TaiKhoan", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("khachHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ThietBi", b =>
                {
                    b.Navigation("ChiTietPhieuDats");

                    b.Navigation("GioHangs");

                    b.Navigation("HinhAnhThietBis");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
