// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChoThueThietBiXD.Data;

namespace WebChoThueThietBiXD.Migrations
{
    [DbContext(typeof(WebChoThueThietBiXDContext))]
    [Migration("20240530044918_ThietbiDanhmucHinhanh")]
    partial class ThietbiDanhmucHinhanh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebChoThueThietBiXD.Models.DanhMucThietBi", b =>
                {
                    b.Property<int>("maDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maDanhMuc");

                    b.ToTable("DanhMucThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.HinhAnhThietBi", b =>
                {
                    b.Property<int>("maHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("hinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("maThietBi")
                        .HasColumnType("int");

                    b.HasKey("maHinhAnh");

                    b.HasIndex("maThietBi");

                    b.ToTable("HinhAnhThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ThietBi", b =>
                {
                    b.Property<int>("maThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("giaThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("maDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("soLuongCon")
                        .HasColumnType("int");

                    b.Property<string>("tenThietBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maThietBi");

                    b.HasIndex("maDanhMuc");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.HinhAnhThietBi", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.ThietBi", "ThietBi")
                        .WithMany("HinhAnhThietBis")
                        .HasForeignKey("maThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ThietBi", b =>
                {
                    b.HasOne("WebChoThueThietBiXD.Models.DanhMucThietBi", "DanhMucThietBi")
                        .WithMany("ThietBis")
                        .HasForeignKey("maDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucThietBi");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.DanhMucThietBi", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("WebChoThueThietBiXD.Models.ThietBi", b =>
                {
                    b.Navigation("HinhAnhThietBis");
                });
#pragma warning restore 612, 618
        }
    }
}
